<?php

namespace ermakk\changelog\widgets\logRowDecode;

use common\models\ProductCategory;
use common\models\TaskStatus;
use common\models\User;
use ermakk\morpherru\widgets\Morpherru;
use yii\base\Widget;
use yii\helpers\Html;
use yii\helpers\Url;

class LogRowDecode extends Widget
{

    public $row;
    public $classLabelList = [];
    public $url = '/view';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $fields = json_decode($this->row->fields,true);
        $res = \Yii::t('ermakk-changelog', 'Пользователь {username} {action} ', [
            'username' => User::find()->where(['id' => $this->row->user_id])->one()->username,
            'action' => $this->row->action == 'update' ? 'обновил' : ( $this->row->action == 'insert' ? 'создал' : 'удалил'),
        ]);
        if ($this->row->action != 'delete')
        {
            $res .= Html::a(
                $this->classLabelList[$this->row->model].' id:'.$this->row->row_id,
                [
                    '/'.strtolower((new \ReflectionClass($this->row->model))->getShortName()).$this->url,
                    'id' => $this->row->row_id
                ]
            );
        } else {
            $res .= $this->classLabelList[$this->row->model].' '.$this->row->comment;
        }

        if ($this->row->action == 'update') {
            if (count(json_decode($this->row->fields,true)) == 1 && array_key_exists('category_id', json_decode($this->row->fields,true))) {
                return $res.' Изменен категорию на: "'.ProductCategory::find()->where(['id' => json_decode($this->row->fields,true)['category_id']])->one()->title.'"';
            } else {
                return $res . ' Изменены поля: ' . json_encode(json_decode($this->row->fields, true), JSON_UNESCAPED_UNICODE);
            }
        } elseif ($this->row->action == 'insert') {

            return $res;
        } elseif ($this->row->action == 'delete') {
            return $res;
        }
    }

}